service: payment-lambda

useDotenv: true

provider:
  name: aws
  runtime: nodejs14.x
  stage: ${opt:stage, self:custom.defaultStage}
  region: ap-northeast-1

custom:
  defaultStage: live
  environment:
    test:
      NEXT_TEST_STRIPE_SECRET_KEY: ${env:NEXT_TEST_STRIPE_SECRET_KEY}
    live:
      NEXT_LIVE_STRIPE_SECRET_KEY: ${env:NEXT_LIVE_STRIPE_SECRET_KEY}

functions:
  checkout:
    handler: checkout.handler
    environment: ${self:custom.environment.${self:provider.stage}}
    events:
      - http:
          path: checkout
          method: POST
          cors: true
